apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: ingress-nginx-scaler
  namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx-scaler
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx-scaler
subjects:
- kind: ServiceAccount
  name: ingress-nginx-scaler
  namespace: keda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-external-scaler
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx-external-scaler
  template:
    metadata:
      labels:
        app: ingress-nginx-external-scaler
    spec:
      containers:
      - name: scaler
        image: keda-ingress-nginx-scaler:v0.0.1 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9443
        args:
        - --port=9443
        - --label-selector=app.kubernetes.io/name=ingress-nginx
        - --v=6
      serviceAccountName: ingress-nginx-scaler
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-external-scaler
  namespace: keda
spec:
  ports:
  - port: 9443
    targetPort: 9443
  selector:
    app: ingress-nginx-external-scaler
