apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrk
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wrk
    spec:
      containers:
      - command:
        - sh
        - -c
        - sleep 10000d
        image: skandyla/wrk:latest
        imagePullPolicy: IfNotPresent
        name: wrk